version: "3.8"

services:
  backend:
    build:
      context: . # Root context
      dockerfile: backend/Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - HOST=${WS_URL}
      - SOCKET_KEY=${SOCKET_KEY}
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: . # Root context
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - WS_URL=${WS_URL}
      - SOCKET_KEY=${SOCKET_KEY}
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    restart: unless-stopped
